version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: alpine:latest  # Use the official Alpine Linux image
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"
    volumes:
      - ./your_sqlite_data_directory:/var/lib/sqlite

