version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: sqlite
    volumes:
      - ./your_sqlite_data_directory:/var/lib/sqlite
